spring:
  config:
    import: optional:classpath:application-generated.yml
  cassandra:
    contact-points: cassandra
    port: 9042
    keyspace-name: lending
    local-datacenter: datacenter1
    schema-action: create_if_not_exists
  kafka:
    bootstrap-servers: kafka:9092

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus


api:
  loan:
    base-path: ${API_LOAN_BASE_PATH:/api/loans}
    submit-loan-propositions-path: ${API_LOAN_SUBMIT_LOAN_PROPOSITIONS_PATH:/propositions/submit}
    get-loan-propositions-path: ${API_LOAN_GET_LOAN_PROPOSITIONS_PATH:/propositions}